### ISSUE TITLE
Help page  content

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/IEK#18]

**Comment by StephanievG** [comment]
Have added to following google doc "Calendar - data entry fields" tab - "help" information that goes against each of the proposed fields:
https://docs.google.com/spreadsheets/d/12cu2SzSJhaaNBzdHH6GKyfEQYX_rc8PEb4zneE1Suls/edit#gid=842624034

**Comment by sat01a** [comment]
Issue moved to [AtlasOfLivingAustralia/seasonal-calendar #12](https://github.com/AtlasOfLivingAustralia/seasonal-calendar/issues/12) via [**ZenHub**](https://www.zenhub.com/)
