### ISSUE TITLE
Design and implement project level metadata  

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/IEK#9]

**Comment by sat01a** [comment]
TODO - Stephanie to provide details (4 Components)

**Comment by StephanievG** [comment]
See google doc "Calendar-data entry fields" for fields: 
https://docs.google.com/spreadsheets/d/12cu2SzSJhaaNBzdHH6GKyfEQYX_rc8PEb4zneE1Suls/edit#gid=842624034
